global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: 'crypto_backend'
    static_configs:
      - targets: ['localhost:8000'] 

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:8000'] 
